version: 0.2
run-as: root

phases:
  install:
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.1.0.4477-linux-x64.zip
      - unzip sonar-scanner-cli-6.1.0.4477-linux-x64.zip
      - export PATH=$PATH:./sonar-scanner-6.1.0.4477-linux/bin/
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.......
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URL
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_NUMBER)
  build:
    commands:
      - echo Start sonar scanning
      - sonar-scanner -Dsonar.projectKey=codepipeline-project-key -Dsonar.sources=. -Dsonar.host.url=$sonar_url -Dsonar.token=$sonar_token
      - echo Build started on `date`
      - echo Docker image is building... 
      - npm --version
      - npm install express
      - npm install prom-client
      - docker build -t $REPOSITORY_URL:latest .
      - docker tag $REPOSITORY_URL:latest $REPOSITORY_URL:$IMAGE_TAG    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to AWS ECR .....
      - docker push $REPOSITORY_URL:$IMAGE_TAG 
      - echo ECS Configuration....
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URL:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json   
artifacts:
    files: imagedefinitions.json
